name: Using Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: react-a

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test